stages:
  - build

image: $CI_DOCS_DOCKER_IMAGE

build:
  stage: build
  before_script:
    - pip3 install -r requirements.txt
  script:
    - make html
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - build
      - $CI_DOCS_ARCHIVE

deploy:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
