name: Build docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docs-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          python -m pip install -r requirements.txt
      - name: Generate documentation
        run: |
          cd source
          make html
      - uses: actions/upload-artifact@v3
        with:
          name: gh-page
          path: source/build/html
