name: Documentation build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Install dependencies
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            python3 python3-pip
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Build Docs
        run: |
          pushd docs
            pip3 install -r requirements.txt
            TZ=UTC make html
          popd
          ls -lah docs/build
      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs/build
