name: Build docs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install -r requirements.txt
      - name: Generate documentation
        run: |
          make html
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build_outputs_folder/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        pages: write
        id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
